#!/usr/bin/env bash
set -e

function _usage {
  echo "The script checks for pods to reach ready status."
  echo "It runs kubectl wait in a loop, and provides stdout output for codefresh. "
  echo ""
  echo "usage: kait-for-it -n namespace -p pod-name [-t timeout] | [-h]"
  echo ""
  echo "-n, --namespace    namespace to target"
  echo "-t, --timeout      timeout, in minutes"
  echo "-p, --pod          pods to target, supports glob, can be used multiple times."
}

if [ "${#}" -eq 0 ]; then
  _usage
  exit 1
fi

while [ "$1" != "" ]; do
  case "${1}" in
    -t | --timeout )
      shift
      timeout="${1}"
      ;;
    -n | --namespace )
      shift
      namespace="${1}"
      ;;
    -p | --pod )
      shift
      targeted_pods="${1} ${targeted_pods}"
      ;;
    -h | --help )
      _usage
      exit 0
      ;;
    * )
      _usage
      exit 1
  esac
  shift
done

let timeout=${timeout:-10}*2
if [ -z ${namespace} ]; then
  namespace=$(kubectl config view --minify --output 'jsonpath={..namespace}')
fi

function _select_pods() {
  running_pods=$(kubectl --namespace ${namespace} get pod --no-headers --field-selector status.phase!=Terminating -o custom-columns=:metadata.name)
  for i in $running_pods; do
    for j in $targeted_pods; do
      if [[ "$i" == ${j} ]]; then
        selected_pods="pod/$i $selected_pods"
      fi
    done
  done
  if [ -z "${selected_pods}" ]; then
    echo "No pods found. Failing."
    exit 2
  fi
}

function _wait_for_pods() {
  kubectl wait --namespace ${namespace} --timeout=10s --for=condition=ready ${selected_pods}
}

_select_pods
_wait_for_pods
pod_status=$?

iteration=0
until [ ${pod_status} -eq 0 ] || [ ${iteration} -ge ${timeout:-10} ]; do
  sleep 30
  let iteration=${iteration}+1
  _select_pods
  _wait_for_pods
  pod_status=$?
done

if [ ${pod_status} -eq 0 ]; then
  echo "Selected pods ready."
else
  echo "Timed out."
fi
exit ${pod_status}
