name: Build

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  main:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: docker build --tag ironhalik/env2helm .

      - name: Push
        run: |
          echo "${{ secrets.DOCKER_HUB_PASS }}" | docker login -u ironhalik --password-stdin
          [ ${GITHUB_REF##*/} == "master" ] && TAG="latest" || TAG=${GITHUB_REF##*/}
          echo "Pushing tag: ${TAG}"
          docker tag ironhalik/env2helm ironhalik/env2helm:${TAG}
          docker push ironhalik/env2helm:${TAG}
