name: Docker build

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  main:
    runs-on: ubuntu-18.04
    steps:
      - name: git pull
        uses: actions/checkout@v2

      - name: docker login
        run: echo "${{ secrets.DOCKER_HUB_PASS }}" | docker login -u ironhalik --password-stdin

      - name: docker build
        run: docker build --tag ironhalik/env2helm .

      - name: docker push
        if: success() && github.ref == 'refs/heads/master'
        run: |
          [ ${GITHUB_REF##*/} == "master" ] && TAG="latest" || TAG=${GITHUB_REF##*/}
          docker tag ironhalik/env2helm ironhalik/env2helm:${TAG}
          docker push ironhalik/env2helm:${TAG}
